### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Annu33202** [mincrmatt12/nelson-pdf-downloader#2]
Hi,
    I'm trying to download pdf from "Mynelson" and I'm getting this error can you check this I've installed everything that was prerequired.

Here is the [image](https://i.imgur.com/iuMZFhS.png) that I've run

And here is the output

> Product ID (find url of explorer pid): 7411011
Session ID (find by logging in and copying it): BD2695E621D677CDCCEEC2F9E4DC9B03
Server ID (weird tomcat server id): 2983305738.17695.0000
Using book Functions 11
Traceback (most recent call last):
  File "./main.py", line 30, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./main.py", line 22, in main
    urls, names = tree.get_tree_url(book, tree_index)
  File "/home/daxxling/Downloads/Compressed/nelson-pdf-downloader-master/tree.py", line 21, in get_tree_url
    if len(book_obj) < tree_index + 1:
  File "/home/daxxling/Downloads/Compressed/nelson-pdf-downloader-master/niter.py", line 89, in __len__
    return len(self.info["NavLevelTitleList"])
TypeError: object of type 'NoneType' has no len()

**Comment by mincrmatt12** [comment]
Hi!

The tool only works for nelson ebooks that are downloadable as separate PDFs through the UI. The book you're looking at is an eBook format (using their weird ebook viewer). To solve your problem, use the "Functions 11 Online Student E-version PDF Files" product instead of the "Functions 11 eBook".

You should be able to run the program with `python3 main.py --tree-index 0` and using product ID 1395206.

**Comment by mincrmatt12** [comment]
I'm closing this due to inactivity, but if you still have a problem after trying the above please do re-open it.
